// Generated by gencpp from file task_manager/Tasksrv.msg
// DO NOT EDIT!


#ifndef TASK_MANAGER_MESSAGE_TASKSRV_H
#define TASK_MANAGER_MESSAGE_TASKSRV_H

#include <ros/service_traits.h>


#include <task_manager/TasksrvRequest.h>
#include <task_manager/TasksrvResponse.h>


namespace task_manager
{

struct Tasksrv
{

typedef TasksrvRequest Request;
typedef TasksrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Tasksrv
} // namespace task_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task_manager::Tasksrv > {
  static const char* value()
  {
    return "8bcfa7c56e0fb0577520f0ba123ec0b4";
  }

  static const char* value(const ::task_manager::Tasksrv&) { return value(); }
};

template<>
struct DataType< ::task_manager::Tasksrv > {
  static const char* value()
  {
    return "task_manager/Tasksrv";
  }

  static const char* value(const ::task_manager::Tasksrv&) { return value(); }
};


// service_traits::MD5Sum< ::task_manager::TasksrvRequest> should match
// service_traits::MD5Sum< ::task_manager::Tasksrv >
template<>
struct MD5Sum< ::task_manager::TasksrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task_manager::Tasksrv >::value();
  }
  static const char* value(const ::task_manager::TasksrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task_manager::TasksrvRequest> should match
// service_traits::DataType< ::task_manager::Tasksrv >
template<>
struct DataType< ::task_manager::TasksrvRequest>
{
  static const char* value()
  {
    return DataType< ::task_manager::Tasksrv >::value();
  }
  static const char* value(const ::task_manager::TasksrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task_manager::TasksrvResponse> should match
// service_traits::MD5Sum< ::task_manager::Tasksrv >
template<>
struct MD5Sum< ::task_manager::TasksrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task_manager::Tasksrv >::value();
  }
  static const char* value(const ::task_manager::TasksrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task_manager::TasksrvResponse> should match
// service_traits::DataType< ::task_manager::Tasksrv >
template<>
struct DataType< ::task_manager::TasksrvResponse>
{
  static const char* value()
  {
    return DataType< ::task_manager::Tasksrv >::value();
  }
  static const char* value(const ::task_manager::TasksrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK_MANAGER_MESSAGE_TASKSRV_H
