// Generated by gencpp from file task_manager/Taskmsg.msg
// DO NOT EDIT!


#ifndef TASK_MANAGER_MESSAGE_TASKMSG_H
#define TASK_MANAGER_MESSAGE_TASKMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task_manager
{
template <class ContainerAllocator>
struct Taskmsg_
{
  typedef Taskmsg_<ContainerAllocator> Type;

  Taskmsg_()
    : taskId(0)
    , description()
    , completed(false)  {
    }
  Taskmsg_(const ContainerAllocator& _alloc)
    : taskId(0)
    , description(_alloc)
    , completed(false)  {
  (void)_alloc;
    }



   typedef int32_t _taskId_type;
  _taskId_type taskId;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _description_type;
  _description_type description;

   typedef uint8_t _completed_type;
  _completed_type completed;





  typedef boost::shared_ptr< ::task_manager::Taskmsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task_manager::Taskmsg_<ContainerAllocator> const> ConstPtr;

}; // struct Taskmsg_

typedef ::task_manager::Taskmsg_<std::allocator<void> > Taskmsg;

typedef boost::shared_ptr< ::task_manager::Taskmsg > TaskmsgPtr;
typedef boost::shared_ptr< ::task_manager::Taskmsg const> TaskmsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task_manager::Taskmsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task_manager::Taskmsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task_manager::Taskmsg_<ContainerAllocator1> & lhs, const ::task_manager::Taskmsg_<ContainerAllocator2> & rhs)
{
  return lhs.taskId == rhs.taskId &&
    lhs.description == rhs.description &&
    lhs.completed == rhs.completed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task_manager::Taskmsg_<ContainerAllocator1> & lhs, const ::task_manager::Taskmsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::task_manager::Taskmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task_manager::Taskmsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task_manager::Taskmsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task_manager::Taskmsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task_manager::Taskmsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task_manager::Taskmsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task_manager::Taskmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0270645c882f00d5a89cc03887a7c6ff";
  }

  static const char* value(const ::task_manager::Taskmsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0270645c882f00d5ULL;
  static const uint64_t static_value2 = 0xa89cc03887a7c6ffULL;
};

template<class ContainerAllocator>
struct DataType< ::task_manager::Taskmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task_manager/Taskmsg";
  }

  static const char* value(const ::task_manager::Taskmsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task_manager::Taskmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 taskId\n"
"string description\n"
"bool completed\n"
;
  }

  static const char* value(const ::task_manager::Taskmsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task_manager::Taskmsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.taskId);
      stream.next(m.description);
      stream.next(m.completed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Taskmsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task_manager::Taskmsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task_manager::Taskmsg_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "taskId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.taskId);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.description);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "completed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.completed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK_MANAGER_MESSAGE_TASKMSG_H
