// Generated by gencpp from file task_manager/TasksrvRequest.msg
// DO NOT EDIT!


#ifndef TASK_MANAGER_MESSAGE_TASKSRVREQUEST_H
#define TASK_MANAGER_MESSAGE_TASKSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task_manager
{
template <class ContainerAllocator>
struct TasksrvRequest_
{
  typedef TasksrvRequest_<ContainerAllocator> Type;

  TasksrvRequest_()
    : action(0)
    , taskId(0)
    , description()
    , completed(false)  {
    }
  TasksrvRequest_(const ContainerAllocator& _alloc)
    : action(0)
    , taskId(0)
    , description(_alloc)
    , completed(false)  {
  (void)_alloc;
    }



   typedef int32_t _action_type;
  _action_type action;

   typedef int32_t _taskId_type;
  _taskId_type taskId;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _description_type;
  _description_type description;

   typedef uint8_t _completed_type;
  _completed_type completed;





  typedef boost::shared_ptr< ::task_manager::TasksrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task_manager::TasksrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TasksrvRequest_

typedef ::task_manager::TasksrvRequest_<std::allocator<void> > TasksrvRequest;

typedef boost::shared_ptr< ::task_manager::TasksrvRequest > TasksrvRequestPtr;
typedef boost::shared_ptr< ::task_manager::TasksrvRequest const> TasksrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task_manager::TasksrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task_manager::TasksrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task_manager::TasksrvRequest_<ContainerAllocator1> & lhs, const ::task_manager::TasksrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action &&
    lhs.taskId == rhs.taskId &&
    lhs.description == rhs.description &&
    lhs.completed == rhs.completed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task_manager::TasksrvRequest_<ContainerAllocator1> & lhs, const ::task_manager::TasksrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::task_manager::TasksrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task_manager::TasksrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task_manager::TasksrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task_manager::TasksrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task_manager::TasksrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task_manager::TasksrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task_manager::TasksrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adb802e061af84b18d3d83f313e6fb85";
  }

  static const char* value(const ::task_manager::TasksrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xadb802e061af84b1ULL;
  static const uint64_t static_value2 = 0x8d3d83f313e6fb85ULL;
};

template<class ContainerAllocator>
struct DataType< ::task_manager::TasksrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task_manager/TasksrvRequest";
  }

  static const char* value(const ::task_manager::TasksrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task_manager::TasksrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 action\n"
"int32 taskId\n"
"string description\n"
"bool completed\n"
;
  }

  static const char* value(const ::task_manager::TasksrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task_manager::TasksrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.taskId);
      stream.next(m.description);
      stream.next(m.completed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TasksrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task_manager::TasksrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task_manager::TasksrvRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "action: ";
    Printer<int32_t>::stream(s, indent + "  ", v.action);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "taskId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.taskId);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.description);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "completed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.completed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK_MANAGER_MESSAGE_TASKSRVREQUEST_H
